# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: testpool 
      vmImage: ubuntu-latest
    steps:
    - bash: sudo apt install docker.io -y
      displayName: 'Upgrade Azure CLI'
    - bash: sudo chmod 777 /var/run/docker.sock
      displayName: 'Upgrade Azure CLI'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/result/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'votingappcontainerRegistrydev'
        repository: 'examplevotingapp_result'
        command: 'push'
        tags: 'latest'