# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: testpool 
      vmImage: ubuntu-latest
    steps:
    - bash: sudo apt install docker.io -y
      displayName: 'Install docker package'
    - bash: sudo chmod 777 /var/run/docker.sock
      displayName: 'Enable permission for docker'
    - task: Docker@2
      displayName: 'build result app'
      inputs:
        containerRegistry: 'votingappcontainerRegistrydev'
        repository: 'examplevotingapp_result'
        command: 'buildAndPush'
        Dockerfile: '**/result/Dockerfile'
        tags: latest
    - task: Docker@2
      displayName: 'build vote app'
      inputs:
        containerRegistry: 'votingappcontainerRegistrydev'
        repository: 'examplevotingapp_vote'
        command: 'buildAndPush'
        Dockerfile: '**/vote/Dockerfile'
        tags: latest
    - task: Docker@2
      displayName: 'build workser svc'
      inputs:
        containerRegistry: 'votingappcontainerRegistrydev'
        repository: 'examplevotingapp_worker'
        command: 'buildAndPush'
        Dockerfile: '**/worker/Dockerfile'
        tags: latest
        arguments: '--build-arg BUILDPLATFORM=linux --build-arg TARGETPLATFORM=linux/amd64'
    